<%@ Page language="c#" codePage="936" CodeBehind="emot.aspx.cs" AutoEventWireup="false" Inherits="KxdInfo.KM.Interface.QueryInfoManage.HtmlEditor.emot" %>
<html>
<head>
<title>单击表情图标即可自动插入</title>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Window-target" content="_top">
<meta http-equiv="Content-Language" content="zh-cn">
<meta http-equiv="Content-Type" content="text/html; charset=gb2312">
<style type="text/css">
<!--td {font-size: 9pt;}-->
</style>
<body bgcolor="#efefef" topmargin="0"></head><table width="220" border="0" align="center" cellpadding="2" cellspacing="2"><tr>
    <td colspan="3" align="center"> <p><img style="cursor:hand" src="emot/emsmile.gif" onclick='window.returnValue ="emot/emsmile.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emteeth.gif" onclick='window.returnValue ="emot/emteeth.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emwink.gif" onclick='window.returnValue ="emot/emwink.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emsmileo.gif" onclick='window.returnValue ="emot/emsmileo.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emsmilep.gif" onclick='window.returnValue ="emot/emsmilep.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emsmiled.gif" onclick='window.returnValue ="emot/emsmiled.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emangry.gif" onclick='window.returnValue ="emot/emangry.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emembarrassed.gif" onclick='window.returnValue ="emot/emembarrassed.gif";window.close();' width="19" height="19"></p></td></tr><tr>
    <td colspan="3" align="center"><img style="cursor:hand" src="emot/emcrook.gif" onclick='window.returnValue ="emot/emcrook.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emsad.gif" onclick='window.returnValue ="emot/emsad.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emcry.gif" onclick='window.returnValue ="emot/emcry.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emdgust.gif" onclick='window.returnValue ="emot/emdgust.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emangel.gif" onclick='window.returnValue ="emot/emangel.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emlove.gif" onclick='window.returnValue ="emot/emlove.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emunlove.gif" onclick='window.returnValue ="emot/emunlove.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emmessag.gif" onclick='window.returnValue ="emot/emmessag.gif";window.close();' width="19" height="19"></td>
  </tr><tr>
    <td colspan="3" align="center"><img style="cursor:hand" src="emot/emcat.gif" onclick='window.returnValue ="emot/emcat.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emdog.gif" onclick='window.returnValue ="emot/emdog.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emmoon.gif" onclick='window.returnValue ="emot/emmoon.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emstar.gif" onclick='window.returnValue ="emot/emstar.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emfilm.gif" onclick='window.returnValue ="emot/emfilm.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emnote.gif" onclick='window.returnValue ="emot/emnote.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emrose.gif" onclick='window.returnValue ="emot/emrose.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emrosesad.gif" onclick='window.returnValue ="emot/emrosesad.gif";window.close();' width="19" height="19"></td>
  </tr><tr>
    <td colspan="3" align="center"><img style="cursor:hand" src="emot/emclock.gif" onclick='window.returnValue ="emot/emclock.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emlips.gif" onclick='window.returnValue ="emot/emlips.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emgift.gif" onclick='window.returnValue ="emot/emgift.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emcake.gif" onclick='window.returnValue ="emot/emcake.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emphoto.gif" onclick='window.returnValue ="emot/emphoto.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emidea.gif" onclick='window.returnValue ="emot/emidea.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emtea.gif" onclick='window.returnValue ="emot/emtea.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emphone.gif" onclick='window.returnValue ="emot/emphone.gif";window.close();' width="19" height="19"></td>
  </tr><tr>
    <td colspan="3" align="center"><img style="cursor:hand" src="emot/emhug.gif" onclick='window.returnValue ="emot/emhug.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emhug2.gif" onclick='window.returnValue ="emot/emhug2.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/embeer.gif" onclick='window.returnValue ="emot/embeer.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emcocktl.gif" onclick='window.returnValue ="emot/emcocktl.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emfemale.gif" onclick='window.returnValue ="emot/emfemale.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emmale.gif" onclick='window.returnValue ="emot/emmale.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emthup.gif" onclick='window.returnValue ="emot/emthup.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emthdown.gif" onclick='window.returnValue ="emot/emthdown.gif";window.close();' width="19" height="19"></td>
  </tr><tr><td width="3">&nbsp;</td><td width="103"><img style="cursor:hand" src="emot/emvamp.gif" onClick='window.returnValue ="emot/emvamp.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emhot.gif" onClick='window.returnValue ="emot/emhot.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/emrainbow.gif" onClick='window.returnValue ="emot/emrainbow.gif";window.close();' width="19" height="19">&nbsp;<img style="cursor:hand" src="emot/ememail.gif" onClick='window.returnValue ="emot/ememail.gif";window.close();' width="19" height="19"></td><td width="94"><div align="center"><a style="cursor:hand" onclick='window.returnValue =" ";window.close();'>更多表情&gt;&gt;</a></div></td></tr></table></body></html>
